# comenzamos con una imagen ligera de python
FROM python:3.11-slim

# evita la creación de archivos .pyc y forzar salida sin buffer para logs
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PATH="/app/.venv/bin:$PATH"

    # directorio de trabajo dentro del contenedor
WORKDIR /app

# -- dependencias del sistema necesarias para PostgreSQL --
RUN apt-get update && apt-get install -y \
        libpq-dev gcc \
        && rm -rf /var/lib/apt/lists/*

# descargamos uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# copiamos los archivos de dependencias
COPY pyproject.toml uv.lock ./

# instalamos las dependencias
RUN uv sync --frozen --no-dev

# 1. crear usuario no privilegiado y copiar el código
RUN useradd -m web-user
COPY --chown=web-user:web-user . .

# 2. copiar y hacer ejecutable el entrypoint DESPUÉS del COPY . .
#    (como root, para que el bit de ejecución no sea sobreescrito ni perdido)
COPY entrypoint.sh /app/entrypoint.sh
RUN sed -i 's/\r$//' /app/entrypoint.sh \
    && chmod +x /app/entrypoint.sh

# 3. cambiar al usuario no privilegiado para la ejecución
USER web-user

ENTRYPOINT ["/app/entrypoint.sh"]

EXPOSE ${APP_PORT}