services:
  grupo7_db:
    image: postgres:15-alpine
    env_file:
      - .env
    # persistencia de datos
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # saber si el servicio está realmente funcionando (no solo corriendo)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    # red docker en el server del ramo
    # networks:
    #   - red_taller_software
    
  grupo7_app:
    build: 
      context: ./asistencia_lsmb  # contruir esta imagen a partir de esta ruta
      dockerfile: dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    # agregado para poder desarrollar en docker
    volumes: 
      - ./asistencia_lsmb:/app
      - /app/.venv # utiliza el venv que creó (ya no se copia desde los archivos)
    env_file:
      - .env
    depends_on:
      grupo7_db:
        condition: service_healthy
    # red docker en el server del ramo
    # networks:
    #   - red_taller_software
  

volumes:
  postgres_data:

# networks:
#   red_taller_software:
#     external: true
    # driver: bridge # ??