services:
  db:
    image: postgres:15-alpine
    # variables de entorno - docker autoconfigura postgresql
    env_file: # produccion - se busca el .env
      - path: .env
        required: false
    environment: # si no (producción), se busca en el sistema (se deben añadir al path mediante ssh)
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

    # persistencia de datos
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
  web:
    build:
      context: ./asistencia_lsmb  # contruir esta imagen a partir de esta ruta
      dockerfile: dockerfile
    # comando para iniciar la aplicación django
    command: uv run manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000" 
    # agregado para poder desarrollar en docker
    volumes:
      - ./asistencia_lsmb:/app
    env_file:
      - path: .env
        required: false
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

    depends_on:
      - db

volumes:
  postgres_data: