services:
  db:
    image: postgres:15-alpine
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    # persistencia de datos
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # saber si el servicio está realmente funcionando (no solo corriendo)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  web:
    build: 
      context: ./asistencia_lsmb  # contruir esta imagen a partir de esta ruta
      dockerfile: dockerfile
    # comando para iniciar la aplicación django
    command: >
      sh -c "uv run manage.py migrate &&
             uv run manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000" 
    # agregado para poder desarrollar en docker
    volumes: 
      - ./asistencia_lsmb:/app
      - /app/.venv # utiliza el venv que creó (ya no se copia desde los archivos)
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - UV_LINK_MODE=copy 
    depends_on:
      db:
        condition: service_healthy
  

volumes:
  postgres_data: