# Generated by Django 5.2.17 on 2026-09-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_alter_curso_profesor_jefe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('umbral_minimo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('genera_alerta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='alertas.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('revisada', models.BooleanField(default=False)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='academico.alumno')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='academico.periodoacademico')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='alertas.estado')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='alertas.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='academico.alumno')),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_anteriores', to='alertas.estado')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_nuevos', to='alertas.estado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados_alumno', to='academico.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_alerta', to='alertas.cargo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='alertas.estado')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('estado', 'cargo'), name='uq_config_alerta_estado_cargo')],
            },
        ),
        migrations.CreateModel(
            name='EstadoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='academico.alumno')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_alumno', to='alertas.estado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_alumno', to='academico.periodoacademico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('alumno', 'periodo'), name='uq_estado_alumno_periodo')],
            },
        ),
    ]
