# Generated by Django 5.2.17 on 2026-09-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_alter_curso_profesor_jefe'),
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados_Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('es_estado_final', models.BooleanField(default=False)),
                ('cubre_ausencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('cuenta_como_ausencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Justificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField(blank=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
                ('estado_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencia.estados_solicitud')),
                ('funcionario_resuelve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='justificaciones_resueltas', to='alertas.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Paso_Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(default='unica', max_length=20)),
                ('fecha', models.DateField()),
                ('hora_registro', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasos_lista', to='alertas.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
                ('justificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='asistencia.justificaciones')),
                ('paso_lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.paso_lista')),
                ('tipo_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.tipos_asistencia')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paso_lista',
            constraint=models.UniqueConstraint(fields=('curso', 'fecha', 'jornada'), name='uq_paso_lista_curso_fecha_jornada'),
        ),
        migrations.AddConstraint(
            model_name='asistencia_alumnos',
            constraint=models.UniqueConstraint(fields=('paso_lista', 'alumno'), name='uq_asistencia_paso_lista_alumno'),
        ),
    ]
