# Generated by Django 5.2.17 on 2026-09-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.SmallIntegerField(unique=True, verbose_name='Año')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Periodos Académicos',
            },
        ),
        migrations.CreateModel(
            name='AlumnoApoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(max_length=30)),
                ('recibe_notificaciones', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.apoderado')),
            ],
            options={
                'verbose_name_plural': 'Relaciones Alumno-Apoderado',
                'unique_together': {('alumno', 'apoderado')},
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='apoderados',
            field=models.ManyToManyField(through='academico.AlumnoApoderado', to='academico.apoderado'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor_jefe', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('grupo', models.CharField(max_length=3)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academico.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academico.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academico.curso')),
                ('estado_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.estadomatricula')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodoacademico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_termino__isnull', True)), fields=('alumno', 'periodo'), name='uq_matricula_alumno_periodo_vigente')],
            },
        ),
    ]
