# Generated by Django 5.2.17 on 2026-09-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor_jefe',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
